"use client";
import { QueryClient, QueryClientProvider } from "react-query";

import "./globals.css";

// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={``}>{children}</body>
      </QueryClientProvider>
    </html>
  );
}
